Fix type cast bug with numpy 1.7
meshgrid upcasts float32 to float64 as of v1.7. Convert back to float32
before calling cctk.interpolate2d. The error:

TypeError: Cannot cast array data from dtype('float64') to
dtype('float32') according to the rule 'safe'